name: Build Fonts

on:
  push:
    branches:
      - master
    paths:
      - sources/**
  pull_request:
    branches:
      - master
    paths:
      - sources/**
  workflow_dispatch:

jobs:
  static-font-ci-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.14 ]
    name: Build Fonts
    steps:
      - name: Check out JetBrains Mono source repository
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgit2-dev python3-pygit2
      - name: Set up Python v${{ matrix.python-version }} environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python build dependency cache lookup
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # Check for requirements file cache hit
          key: ${{ runner.os }}-pip-${{ hashFiles('${{ steps.config.outputs.dependpath }}') }}
      - name: Install Python build dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-wheel: "true"
          update-setuptools: "true"
      - name: Build fonts
        run: |
          gftools builder sources/config.yaml
          python scripts/generate_variable_webfonts.py
      - name: Upload Fonts
        uses: actions/upload-artifact@v5
        with:
          name: Fonts
          path: fonts/

